### ISSUE TITLE
AttributeError: 'module' object has no attribute 'tripschedualselector'

### ISSUE THREAD

**Issue by double-u-a** [kuanb/ua_pdna_example#1]
This is great, I just this week was trying to figure urbanaccess out last week and suddenly I find your fully worked out example!

I am running through your example script in Jupyter (and also tested on command line) but I am always getting an attribute error on the headway building part of the example.py:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-2dad79d0c741> in <module>()
      4            'unique_agency_id']
      5 day = 'wednesday' # pick an arbitrary day of week
----> 6 tripschedualselector = urbanaccess.gtfs.network.tripschedualselector
      7 cal_selected_trips = tripschedualselector(
      8                                 input_trips_df = loaded_feeds.trips[columns],

AttributeError: 'module' object has no attribute 'tripschedualselector'
```

And I suspect this would also happen for the other two new attributes `interpolatestoptimes` & `intermediate_interpolation`, I tried to look up adding attributes in python but I can't really find anything explaining how this syntax works exactly.

**Comment by sablanchard** [comment]
@double-u-a and @kuanb just wanted to post here that there is a demo up now for UrbanAccess that shows you an entire workflow in a jupyter notebook that can be accessed [here](https://github.com/UDST/urbanaccess/blob/master/demo/simple_example.ipynb). @kuanb not sure what the best way is to re-direct people to the main UrbanAccess repo for the demo, as this demo in this repo may be out of date. Maybe something on the readme page that says that this repo may be out of date and to see the UrbanAccess demo for a up to date version?
